### ISSUE TITLE
開発参加の件

### ISSUE THREAD

**Issue by ymdarake** [groonga/grafana-datasource-plugin-groonga#1]
本日のGroonga勉強会で開発参加のお声かけを頂いた坂本です。
詳しい状況など良く分かっていませんが、よろしくお願いいたします！

（この週末はＰＣを使える環境にいないためお返事が遅れがちになってしまうと思いますが、ご容赦ください。）

**Comment by kou** [comment]
ようこそ！

[Grafana](http://grafana.org/)というのがデータ（1分間隔のCPU使用率とかの統計データやアクセスログなど「時刻」を含んでいるデータ（= 時系列データ））を可視化（グラフでパット見でわかるように）するツールです。データを可視化することにより、データの傾向から問題を発見したり（通常よりCPU使用率が高くなっているのが問題だな！とわかったり）、これから起こるだろう問題を予測したり（このペースでディスク使用量が増えていくと1週間後には容量オーバーになる！今のうちに追加しないと！）ということを支援するツールです。

データは外部のデータベースに保存します。保存する処理はプラグインになっていて、後から追加できるようになっています。Groongaに保存できるようにするプラグインがこのプラグインです。

Groongaに保存されている時系列データをGrafanaで扱えるとなにが嬉しいかというと、可視化する前にデータを全文検索（Groongaは全文検索エンジンです！）でフィルターできることです。たとえば、アプリケーションログを時系列データとして扱っているとき、「Error」と「Groonga」を含むログだけを抽出して可視化することが得意です。

時系列データを可視化するときは数値データ（CPU使用率とかディスク使用量とかHTTPのステータスコード（404とか）とか）を扱うことが多いですが、全文検索を使えると文字列データも扱いやすくなるのでやれることの幅が広がります。

という感じが、概要です。伝わりますか？

これからの進め方ですが、なにはともあれ、まずは動かしてみるのがよいと思います。ということで、[README](https://github.com/groonga/grafana-datasource-plugin-groonga#readme)を見ながら動かしてみましょう！たぶん、途中でいろいろ詰まると思うので、都度聞いてください。

聞く場所ですが、ここにコメントを追記するか、[チャット](https://gitter.im/groonga/grafana-datasource-plugin-groonga)を使うのがいいと思います。

最初はいろいろ詰まってなかなか進まないと思うので、まとめて一気に作業を進めよう！というよりも、毎日少しずつ進める（詰まった！→聞く！→解決→次に進む！）、という方がよいと思います。

**Comment by TakumiSakamoto** [comment]
ご説明ありがとうございます！
大まかには、

Grafanaは、

・外から持ってきたデータをグラフにできる
・データをどこに保存するか、はプラグインで指定できる

ので、

・Groongaに保存するためのプラグインを作ろう！
・そうすれば、全文検索でデータをフィルターできて嬉しい！

という流れですね。

既存のコードをまだ細かく観察できていないですが、
・Groongaにデータを送る部分
・Groongaからデータを引っ張ってくる部分
を作る、ということになるでしょうか。

明日の夜から取り掛かることができるので、まずはいろいろ参考にしつつ動かしてみます！

勉強しつつ取り組むことになりそうなので、本当にたくさんご質問すると思いますが、よろしくお願いいたします！

**Comment by kou** [comment]
自分がどう理解したかを書いてくれてありがとうございます！
どこまで伝わったかがわかってとても助かります。

> ・データをどこに保存するか、はプラグインで指定できる

が違っていて、「データをどこから取得するか」なんです。

なので、

> ・Groongaに保存するためのプラグインを作ろう！

は、「Groongaからデータを取得するためのプラグインを作ろう！」になります。


ということで、

> ・Groongaにデータを送る部分

は作る必要はありません。

> ・Groongaからデータを引っ張ってくる部分

だけです。

ただ、「だけです」、というと少し語弊があって、

  * Groongaからどのようなデータを引っ張ってくるかを指定するUI部分（ようは、どんな条件でグラフ化対象のデータを取得するかというのをユーザーが簡単に指定できるようにするためのフォーム）

も作る必要があります。

> 明日の夜から取り掛かることができるので、まずはいろいろ参考にしつつ動かしてみます！

わかりました！

動かすとき、データが入ったGroongaサーバーが必要になります。 http://packages.groonga.org:10041/ で動いているGroongaサーバーを使っていいです。このGroongaサーバーはGroongaのソースやパッケージを配布しているサーバーのアクセスログを保存しています。このGroongaサーバーに`Logs`テーブルがあるのですが、そこに時系列データが入っています。

> 勉強しつつ取り組むことになりそうなので、本当にたくさんご質問すると思いますが、よろしくお願いいたします！

はい！

**Comment by TakumiSakamoto** [comment]
ご返信が遅れ、すみません。
ご丁寧にご指摘くださりありがとうございます。早い段階で誤解が解消されて助かります！
UI部分の作成についても承知しました。

Groongaサーバーもありがとうございます、取り掛かりやすいです。帰宅次第、実際に動かしながら細かい部分も見ていきます。

それではまた、質問を持ってやって来るかと思いますが、よろしくお願いいたします！
