### ISSUE TITLE
Plugin at risk of deprecation

### ISSUE THREAD

**Issue by sympatheticmoose** [groonga/grafana-datasource-plugin-groonga#14]
Hi there from Grafana Labs 👋 

Firstly, thank you for contributing to the Grafana plugin ecosystem.

I'm reaching out as this plugin is at risk of being [deprecated](https://grafana.com/legal/plugin-deprecation/) from the [Grafana plugin catalog](https://grafana.com/grafana/plugins/) as it has not been updated in 3 years and it is unclear whether it is still maintained.

We recognise that priorities change and that it may no longer be possible to keep plugins up to date. For your awareness, deprecation has no impact on existing users of the plugin, but discourages further adoption to prevent users from starting to rely on a component which won't receive updates.

Please advise if you believe the plugin is stable and wish for it to remain in the catalog, or alternatively that you agree the plugin should be deprecated. In the case of the latter, if there is any specific guidance you would like to offer users of the plugin - please let me know and we can include this in the deprecation notice. 

Feel free to email me at `integrations@grafana.com` if preferred; apologies, we don't have an email address associated with this plugin so I had to raise an issue.

If we don't hear from you within 30 days, I'll go ahead and deprecate the plugin. 

Thank you again
David

**Comment by kou** [comment]
Thanks for contacting us!
We'll update this plugin. Could you keep this plugin as a normal (not deprecated) plugin?

BTW, it seems that `grabpl` is deprecated. ( https://github.com/grafana/build-pipeline/ doesn't exist.) Do you know alternative tool...?

**Comment by sympatheticmoose** [comment]
Hey @kou thanks for getting back to me so quickly 🙌  More than happy to keep your plugin in the catalog knowing there's an update planned. 

From a quick look it doesn't look like `grabpl` is actually being used for your plugin?

`grafana-toolkit` is deprecated, but our new tooling (`create-plugin`) does include a `migrate` cmd to help you. Documentation is available here to walk you through the process https://grafana.com/developers/plugin-tools/migration-guides/migrate-from-toolkit. 

Additionally, create-plugin provides github actions to cover the building and release of the plugin similar to what you have today.

If you hit any issues or have any questions - I'll keep an eye on this issue, but also don't hesitate to reach out in the [community forum](https://community.grafana.com/c/plugin-development/30) or [slack](https://grafana.slack.com/archives/C3HJV5PNE) and that way more of the team/community will also be able to help out.

All the best

**Comment by sympatheticmoose** [comment]
yeah - saw it referenced there, but we couldn't find any reason why the version of toolkit you're running would actually use it

**Comment by kou** [comment]
Does it mean that "why did you pin `grabpl` version by `GRABPL_VERSION=0.5.0` explicitly"?
If so, it's for just creating a download URL: `https://grafana-downloads.storage.googleapis.com/grafana-build-pipeline/v${GRABPL_VERSION}/grabpl`
We needed to specify a version explicitly to download.
